In [1]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

In [2]:
import json
import pyhf
from pyhf.contrib.viz import brazil

In [3]:
data=pd.read_csv('Data.dat',sep=' ')
background=pd.read_csv('Background.dat',sep=' ')
signal1=pd.read_csv('Signal1Higgsdat',sep=' ')
signal2=pd.read_csv('Signal2Axial.dat',sep=' ')

In [4]:
background=background['y'].to_numpy()
data=data['y'].to_numpy()
signal1=signal1['y'].to_numpy()
signal2=signal2['y'].to_numpy()

In [5]:
signal1

array(['101,07672522', '63,095734448', '41,5532169221', '25,6626987327',
       '16,7207523245', '10,6636768725', '6,11007458456', '3,89670630675',
       '2,79583558297', '1,39375374235', '1', '0,651558610364',
       '0,0898438537235', '0,209377607319', '0,148625395482',
       '0,129308748059', '0,188112911249', '0,0824667861422',
       '0,0702282146558', '0,0328306188957', '0,0331841144493',
       '0,0350095111427'], dtype=object)

In [6]:
bkg=np.zeros_like(background)
dt=np.zeros_like(data)
s1=np.zeros_like(signal1)
s2=np.zeros_like(signal2)
for i in range(len(background)):
    bkg[i]=float(background[i].replace(',','.'))
    dt[i]=float(data[i].replace(',','.'))
    s1[i]=float(signal1[i].replace(',','.'))
    s2[i]=float(signal2[i].replace(',','.'))


In [7]:
factor=np.array([30,30,30,30,30,40,40,40,40,40,40,50,50,50,50,50,60,60,60,70,70,90])
len(factor)

22

In [8]:
s1=s1*factor
s2=s2*factor
dt=dt*factor
bkg=dt*factor

In [9]:
errbkg=np.ones_like(bkg)*0.2

In [10]:
bkg

array([4118201.8154550004, 2165897.291868, 1114976.631591,
       625320.9435951001, 366053.7286953, 368901.72017439996,
       202509.57585280002, 118546.14193935998, 69395.17654687999,
       40622.92073951999, 27332.422300960003, 27529.63629475,
       15943.775533425, 8846.616844675, 6081.161261825, 3676.053887725,
       4655.114930123999, 2271.4464401279997, 1495.9158091956,
       1460.8804750197003, 654.3008362736999, 2034.6280095230998],
      dtype=object)

In [11]:
bkg1=np.array([132100,69900,36800,20780,12340,9160,5100,3000,1763,1032,683,554,322,178,122,74.5,77.8,38.4,25.1,21.1,9.4,22.6])
observed=np.array([140642,73114,38321,21417,12525,9515,5174,2947,1777,1021,694,554,339,196,123,80,68,37,23,12,7,26])
errbkg1=np.array([4000,2200,1100,630,400,320,200,120,79,48,37,28,19,13,8,6.6,7.2,4.8,3.4,3.0,1.9,3.0])
len(errbkg1)

22

In [12]:
model1 = pyhf.simplemodels.uncorrelated_background(
    signal=s1.tolist(), bkg=bkg1.tolist(), bkg_uncertainty=errbkg1.tolist()
) #creamos el modelo
model1
print(json.dumps(model1.spec, indent=2)) #Modelo

{
  "channels": [
    {
      "name": "singlechannel",
      "samples": [
        {
          "name": "signal",
          "data": [
            3032.3017566,
            1892.87203344,
            1246.596507663,
            769.880961981,
            501.622569735,
            426.5470749,
            244.4029833824,
            155.86825227,
            111.8334233188,
            55.750149694,
            40.0,
            32.5779305182,
            4.492192686175,
            10.46888036595,
            7.4312697741,
            6.46543740295,
            11.28677467494,
            4.948007168532,
            4.213692879348,
            2.298143322699,
            2.322888011451,
            3.1508560028429997
          ],
          "modifiers": [
            {
              "name": "mu",
              "type": "normfactor",
              "data": null
            }
          ]
        },
        {
          "name": "background",
          "data": [
            132100.0,
           

In [13]:
model2 = pyhf.simplemodels.uncorrelated_background(
    signal=s2.tolist(), bkg=bkg1.tolist(), bkg_uncertainty=errbkg1.tolist()
) #creamos el modelo
model2
print(json.dumps(model2.spec, indent=2)) #Modelo

{
  "channels": [
    {
      "name": "singlechannel",
      "samples": [
        {
          "name": "signal",
          "data": [
            266.6603618025,
            206.2198929354,
            157.7798312658,
            123.3317071704,
            93.35648907839999,
            97.2985801892,
            75.24516449960001,
            53.987417011599995,
            40.0,
            34.80125254216,
            24.969441505160002,
            28.04188562685,
            18.46765976415,
            16.59205722465,
            12.16232252365,
            8.72630663085,
            7.2756563953799995,
            5.001283609614,
            4.351273348332,
            3.7612361206,
            2.8167558360340004,
            5.499067126103999
          ],
          "modifiers": [
            {
              "name": "mu",
              "type": "normfactor",
              "data": null
            }
          ]
        },
        {
          "name": "background",
          "data": [


In [14]:
init_pars1= model1.config.suggested_init()
init_pars2 = model2.config.suggested_init()

In [15]:
bkg_pars1= init_pars1.copy()
bkg_pars1[model1.config.poi_index] = 0
bkg_pars2= init_pars2.copy()
bkg_pars2[model2.config.poi_index] = 0

In [16]:
#observaciones y pdf

observations1 = observed.tolist() + model1.config.auxdata  # this is a common pattern!

model1.logpdf(pars=bkg_pars1, data=observations1)



array([-573.28565847])

In [17]:
observations2 = observed.tolist() + model2.config.auxdata  # this is a common pattern!

model2.logpdf(pars=bkg_pars2, data=observations2)


array([-573.28565847])

In [18]:
poi_values1 = np.linspace(0.1, 5, 50)
obs_limit1, exp_limits1, (scan, results) = pyhf.infer.intervals.upper_limits.upper_limit(
    observations1, model1, poi_values1, level=0.05, return_results=True
)
print(f"Upper limit (obs): μ = {obs_limit1:.4f}")
print(f"Upper limit (exp): μ = {exp_limits1[2]:.4f}")

Upper limit (obs): μ = 0.7632
Upper limit (exp): μ = 0.4762


In [19]:
poi_values2 = np.linspace(0.1, 5, 50)
obs_limit2, exp_limits2, (scan, results) = pyhf.infer.intervals.upper_limits.upper_limit(
    observations2, model2, poi_values2, level=0.05, return_results=True
)
print(f"Upper limit (obs): μ = {obs_limit2:.4f}")
print(f"Upper limit (exp): μ = {exp_limits2[2]:.4f}")

Upper limit (obs): μ = 0.7567
Upper limit (exp): μ = 0.6963
